### ISSUE TITLE
Error on app.customSlotTypes()

### ISSUE THREAD

**Issue by andrewferrier** [matt-kruse/alexa-app-server#15]
The merge that was done under commit 4be78999910307053fc7fe950bb0e46b8512e9f0 seems to have introduced a call to `app.customSlotTypes()`. However, this seems to have caused a regression. When I now start my (`alexa-app-server` and `alexa-app`-based skill), I get an error like this:

```
TypeError: app.customSlotTypes is not a function
    at Object.handle (/Users/xyz/Documents/Projects/xyz123/myprojects/Alexa/node_modules/alexa-app-server/index.js:131:81)
```

It's not clear to me what should be implementing the `customSlotTypes()` method, but I don't see it elsewhere in the whole source code tree for `alexa-app-server` or `alexa-app`.

I see this problem with `alexa-app-server` 2.3.0. If I regress to 2.2.4, it goes away. I am using `alexa-app` 2.3.4.

**Comment by matt-kruse** [comment]
Fixed in Version 2.3.1
