### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by EkiSkyten** [matt-kruse/alexa-app-server#7]
Would it be possible to add a license declaration, similar to alexa-app?

**Comment by bdyer64** [comment]
Yes please, I am using this and need to know how it is licensed.

**Comment by matthewkimber** [comment]
+1

MIT? Apache2?

**Comment by dblock** [comment]
Added an MIT license in https://github.com/matt-kruse/alexa-app-server/pull/23.

**Comment by dblock** [comment]
Closed via https://github.com/matt-kruse/alexa-app-server/pull/23.
